from typing import Any, Optional, Sequence

__version__: str

class LineMatch:
    @property
    def line_number(self) -> int: ...
    @property
    def line(self) -> str: ...
    @property
    def before(self) -> list[str]: ...
    @property
    def after(self) -> list[str]: ...
    @property
    def byte_range(self) -> tuple[int, int]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class FileMatches:
    @property
    def path(self) -> str: ...
    @property
    def matches(self) -> list[LineMatch]: ...
    @property
    def match_count(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class GrepResult:
    @property
    def files(self) -> list[FileMatches]: ...
    @property
    def total_matches(self) -> int: ...
    @property
    def truncated(self) -> bool: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class FileSlice:
    @property
    def path(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def content(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class FileHit:
    @property
    def path(self) -> str: ...
    @property
    def bytes(self) -> int: ...
    @property
    def modified(self) -> Optional[float]: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class DirEntry:
    @property
    def path(self) -> str: ...
    @property
    def is_dir(self) -> bool: ...
    @property
    def depth(self) -> int: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...

class SearchEngine:
    def __init__(
        self,
        root: str = ".",
        *,
        respect_gitignore: bool = True,
        include_hidden: bool = False,
        follow_symlinks: bool = False,
    ) -> None: ...
    @property
    def root(self) -> str: ...
    def grep(
        self,
        pattern: str,
        *,
        literal: bool = False,
        case_insensitive: bool = False,
        globs: Optional[Sequence[str]] = None,
        context_before: int = 0,
        context_after: int = 0,
        max_results: int = 100,
        max_bytes: int = 65536,
        max_line_len: int = 512,
    ) -> GrepResult: ...
    def find_files(self, glob: str, *, max_results: int = 1000) -> list[FileHit]: ...
    def read_lines(self, path: str, start: int, end: int) -> FileSlice: ...
    def list_dir(self, path: str = ".", *, max_depth: int = 1) -> list[DirEntry]: ...
